name: Pull Request

on:
  pull_request:

jobs:
  commitlint:
    #
    # ensures commit messages follow conventional commits
    #
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install --save-dev @commitlint/{config-conventional,cli}
      - run: npx commitlint --from=${{ github.event.pull_request.base.sha }}
  lint:
    #
    # runs golangci-lint
    #
    runs-on: ubuntu-latest
    steps:
      # Checkout code to build.
      - name: Checkout repo
        uses: actions/checkout@v2
      # Setup Go in order to vendor dependencies in a later step.
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1'
      # Use auth to get access to private Git repos for Go code dependencies.
      - name: Configure git for private modules
        env:
          TOKEN: ${{ secrets.GH_CI_PAT }}
          GITHUB_USERNAME: ci-cd
        run: git config --global url."https://${GITHUB_USERNAME}:${TOKEN}@github.com".insteadOf "https://github.com"
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.18','1.19']
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{matrix.go}}
      - name: go vendor
        run: go mod vendor
      - name: go test
        run: go test ./...